config/routes.rb
Rails.application.routes.draw do
  resources :lectures do
    member do
      get 'spam' => 'lectures#spam'
      get 'vote' => 'lectures#vote'
      post :comment
      delete :comment_delete
    end
  end
  resources :courses
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.instructor?
      can %i[create destroy update read], [Course, Lecture]
    else
      can :read, :all
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/course.rb
class Course < ApplicationRecord
    validates :title, presence: { message: 'Course Title Must Be Filled' }
    validates :title, uniqueness: { message: 'Course Name Already Exists' }
    validates :user_id, presence: { message: 'must be filled' }

    belongs_to :user
    has_many :lectures ,dependent: :destroy

end

app/models/lecture.rb
class Lecture < ApplicationRecord
    validates :content, presence: { message: 'must be filled' }
    validates :attachment, presence: { message: 'must be uploaded' }
    validates :user_id, presence: { message: 'User Doesn\'t Exists' }
    validates :course_id, presence: { message: 'must be selected' }

    belongs_to :user
    belongs_to :course
    acts_as_votable
    acts_as_commentable
    

    mount_uploaders :attachment, AttachmentUploader
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  def password_required?
    new_record? ? false : super
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum gender: { male: 0, female: 1, other: 2 }

  acts_as_voter
  has_many :courses, dependent: :destroy
  has_many :lectures, dependent: :destroy

  validates :name, presence: { message: 'Name Should Be Filled' }
  validates :email, presence: { message: 'Email Should Be Filled' }
  validates :gender, presence: { message: 'Gender Should Be Selected' }
  validates :date_of_birth, presence: { message: 'Date Should Be Filled' }
  validates :avatar, presence: { message: 'Avatar Should Be Selected' }

  mount_uploader :avatar, AvatarUploader
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name date_of_birth gender avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name date_of_birth gender avatar])
  end
end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
  # before_action :load_and_authorize_resource
  before_action :authenticate_user!, except: %i[index show]

  private

  def course_params
    params.require(:course).permit(:title, :user_id)
  end
end

app/controllers/lectures_controller.rb
class LecturesController < InheritedResources::Base
  # before_action :load_and_authorize_resource
  before_action :authenticate_user!, except: %i[index show]

  def comment
    @lecture = Lecture.find(params[:id])
    @user_who_commented = current_user.id
    comment = Comment.build_from(@lecture, @user_who_commented, params[:comment])
    comment.save
    redirect_to lecture_path
  end

  def vote
    @lecture = Lecture.find(params[:id])
    if !current_user.liked? @lecture
      @lecture.liked_by current_user
    elsif current_user.liked? @lecture
      @lecture.unliked_by current_user
    end
    redirect_to lecture_path
 end

  def spam
    @lecture = Lecture.find(params[:id])
    @lecture.downvote_from current_user, vote_scope: 'rank'
    redirect_to lecture_path
   end

  def comment_delete
    @comment = Comment.find(params[:comment])
    @lecture = Lecture.find(params[:lecture])
    @comment.delete
    @comment.save
    redirect_to @lecture
  end

  private

  def lecture_params
    params.require(:lecture).permit(:content, :course_id, :user_id,attachment: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <div class="text-danger"> <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2></div>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><div class="text-danger" style="font-size:15px"> <%= message  %></div> </li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "title:" , :style=>'font-size:25px' %>
    <%= form.text_field :title, id: :course_title , :class => 'form-control' %> 
  </div>

  <div class="field">
  
    <%= form.text_field :user_id, id: :user_id  ,value:current_user.id,hidden:true %>
  </div>
<br>
  <div class="actions">
    <%= form.submit :class => 'btn btn-success' ,:style=>'font-size:15px' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>
<br>
<%= link_to 'Show', @course, :style => 'font-size:15px' , :class =>'btn btn-primary' %> |
<%= link_to 'Back', courses_path, :style => 'font-size:15px' , :class =>'btn btn-warning'  %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>
<%# <% if can? :create,@course %> %>
<%= link_to 'New Course', new_course_path, :class => 'btn btn-primary' , :style =>'font-size:15px' %>
<%# <%end%> %>
<table class="table table-striped ">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Created By</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td style="font-size:15px"><%= link_to course.title, course %></td>
        <td style="font-size:15px; color:green"><%= User.find(course.user_id).name %> </td>
        <td><%= link_to 'Show', course , :class =>'btn btn-primary'%></td>
        <%if user_session && current_user.id === course.user_id%>
        <td><%= link_to 'Edit', edit_course_path(course) , :class =>'btn btn-warning'%></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, :class =>'btn btn-danger' %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<br>
<%= link_to 'Back', courses_path, :style => 'font-size:15px' , :class =>'btn btn-warning'  %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center ">
  <strong style="font-size:30px">Title: <%= @course.title %> </strong>
  
   <%if user_session && current_user.id === @course.user_id%>
<%= link_to 'Edit Course', edit_course_path(@course), :style=>'font-size:20px' %> 
<%end%>

</div>

<br>
<%= link_to 'New Lecture' , new_lecture_path , :class =>'btn btn-success' , :style=>'font-size:15px'%>

<div>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th><strong>Lectures:</strong></th>
      <th colspan="2">Action</th>
    </tr>
  </thead>
  <tbody>
<% @course.lectures.each do |lecture| %>
  <tr> <td><%=link_to (raw lecture.content) , lecture , :style=>'font-size:15px'%> </td>  

 <%if user_session && current_user.id === lecture.user_id%>
 <td><%= link_to 'Edit Lecture', edit_lecture_path(lecture) , :class =>'btn btn-warning'%></td>
       <td> <%= link_to 'Delete Lecture', lecture, method: :delete, data: { confirm: 'Are you sure?' } , :class =>'btn btn-danger'%>
       <%end%></td>
        </tr> 

<% end %>
  </tbody>
  </table>

</div>

<br>
<br>
 
<%= link_to 'Courses List', courses_path, :class =>'btn btn-primary' , :style=>'font-size:15px' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineCourses</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

  </head>

  <body>


<nav class="navbar navbar-dark bg-dark">
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
         <% if user_signed_in? %>  
          <li><strong style="color:white; font-size:20px"> Logged in as: <%= current_user.email %></strong> </li>
          <li class="nav-item"> <%= link_to 'Edit profile', edit_user_registration_path,:style=>'font-size:20px' %>  </li>
          <li class="nav-item"> <%= link_to "Logout", destroy_user_session_path, method: :delete, :style=>'font-size:20px'%> </li>
          <li class="nav-item">
          <% else %>
          <li class="nav-item"> <%= link_to "Sign up", new_user_registration_path , :style=>'font-size:20px' %>  </li>  
          <li class="nav-item"> <%= link_to "Login", new_user_session_path, :style=>'font-size:20px' %>  </li> 
          <li class="nav-item"> <%=link_to 'Admin Login', new_admin_user_session_path, :style=>'font-size:20px' %> </li>
          <% end %>
    </ul>
</div>
</nav>
    <%= yield %>
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </body>

</html>

app/views/lectures/_form.html.erb
<%= form_with(model: lecture, local: true) do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation">
     <div class="text-danger"> <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2></div>

      <ul>
      <% lecture.errors.full_messages.each do |message| %>
        <li><div class="text-danger" style="font-size:15px"> <%= message  %></div></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label " Content: ", :style =>'font-size:25px' %>
    <%= form.cktext_area :content, id: :lecture_content  %>
  </div>
<br>
  <div class="field">
    <%= form.label "Attachment:" , :style =>'font-size:25px'%>
    <%= form.file_field :attachment, id: :lecture_attachment %>
  </div>
<br>
  <div class="field">
    <%= form.label :course_id, :style =>'font-size:25px' %>
    <%= form.collection_select :course_id, Course.order(:title), :id ,:title %>
  </div>
<br>
  <div class="field">
     <%= form.text_field :user_id, id: :user_id  ,value:current_user.id,hidden:true %>
  </div>

  <div class="actions">
    <%=  form.submit :class =>'btn btn-success' %> 
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<br>
<%= link_to 'Show', @lecture , :style => 'font-size:15px', :class =>'btn btn-primary' %> 

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lectures</h1>

<%= link_to 'New Lecture', new_lecture_path ,:class=>'btn btn-success' , :style =>'font-size:15px' %>

<table class="table table-striped ">
  <thead class="thead-dark">
    <tr>
      <th>Content</th>
      <th>Attachment</th>
      <th>Course Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%=link_to (raw lecture.content),lecture %></td>
        <td><%= lecture.attachment %></td>
         <td><%= lecture.course.title %></td> 
        <td><%= link_to 'Show', lecture ,:class=>'btn btn-primary' %></td>
        <%if user_session && current_user.id === lecture.user_id%>
        <td><%= link_to 'Edit', edit_lecture_path(lecture),:class=>'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' },:class=>'btn btn-danger' %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form', lecture: @lecture %>
<br>
<%= link_to 'Back', courses_path, :class=>'btn btn-warning', :style =>'font-size:15px' %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<div>
<strong style="font-size:25px">Course Name: <%=link_to @lecture.course.title , @lecture.course %> </strong>
</div>
<br>
<div>
  <strong style="font-size:25px">Content:</strong>
  <span style="font-size:15px"><%=raw  @lecture.content %> </span>

  <%if user_session && current_user.id === @lecture.user_id%>
 <%= link_to 'Edit Lecture', edit_lecture_path(@lecture), :class =>'btn btn-warning' , :style => 'font-size:20px' %>
<%end%>
</div>

<br>
<div>
  <strong style="font-size:25px">Attachment:   <span style='font-size:20px; color:green'><%=@lecture.attachment_in_database%> </span</strong><br>
  <span style="font-size:20px"> <%=  link_to 'Download Attachment', @lecture.attachment_url %></span>
   
</div>
<br>
<hr>


<strong style="font-size:20px; color:red" >Spam Reports</strong>
<br>
<strong style="font-size:20px; color:orange">Spams Number : <%=@lecture.get_downvotes.size %></strong>
<br>





<%= link_to 'Report Abuse',spam_lecture_path , :method=>:get , :class=>'btn btn-danger' , :style=>'font-size:15px' %>
<br>
<hr>

<%= form_tag vote_lecture_path, :method => :get do %>
<strong style="font-size:20px">Likes Count: <%=@lecture.get_likes.size %></strong>   <br>
<% if user_session %>
<% if  !current_user.liked? @lecture %>
    <%= submit_tag "Like", class: "btn btn-success"  , :style => 'font-size:20px' %>   
    <% else%>
    <%= submit_tag 'Dislike', class: "btn btn-danger"  , :style => 'font-size:20px'%> 
    <%end%>
<% end %>
<%end%>

<br>
<hr>

<div>
<strong style="font-size:20px">Comments: </strong>
<br><br>


<% @lecture.comment_threads.each do |comment| %>
  <li> <span style="font-size:15px; color:orange">  User: </span> <span style="font-size:15px"><%= comment.user.name %></span> </li>  
    <span style="font-size:15px; color:blue">Comment :</span> <span style="font-size:15px"><%= comment.body %></span>
    <%if user_session && current_user.id === comment.user_id%>
    <%=link_to 'Delete', comment_delete_lecture_path(:comment=>comment.id,:lecture=>@lecture.id), :method=> :delete , data: { confirm: 'Are you sure?' } , :class =>'btn btn-danger'%>
    <%end%>
<% end %>

<% if user_session %>
<%= form_tag comment_lecture_path, :method => :post do %>

    <%= text_field_tag "comment"  %>

    <%= submit_tag "Submit" , :class =>'btn btn-success'%>
  
<% end %>
<%end%>


</div>